name: stdev_task
description: A new Flutter project.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  bloc: ^8.1.1
  dartz: ^0.10.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  image_picker: ^1.0.2
  injectable: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  kt_dart: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.4
  flutter_native_splash: ^2.2.17
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  lint: ^2.1.2

flutter:
  uses-material-design: true
include:
  - analysis_options.yaml
